# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f5489a144bd4e88e63168c694e3dc1880e2d97c7f32dc0c93acf90b677cb8a26aa263f8cb58584717bf110993475bade9b93037b44768c5f0d209a9b88e1929

test:
  secret_key_base: dd396588a2c996a79f96c2bbd625c2de3ec7799d203ec91f7f31ed3b555eb73f8044ebb841259d56b662a6ac7f18186a578c1eb4a7795057f9969eb8ea52553d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
